- set_fact:
    proxy_squid: {}
  when: >
    proxy_squid is undefined

- set_fact:
    role_packages:
      - squid

- include_role:
    name: data-utilities
    tasks_from: install_packages

- name: configure firewall for squid (default port)
  firewalld:
    zone: "{{__zone}}"
    service: "squid"
    permanent: true
    state: enabled
    immediate: true
  with_items: "{{proxy_squid.firewall_zones}}"
  loop_control:
    loop_var: __zone
  when: >
    (firewalld_available is defined and
    firewalld_available == True) and
    proxy_squid.firewall_zones is defined and
    proxy_squid.port is undefined

- name: configure firewall for squid (custom port)
  firewalld:
    zone: "{{__zone}}"
    port: "{{proxy_squid.port}}/tcp"
    permanent: true
    state: enabled
    immediate: true
  with_items: "{{proxy_squid.firewall_zones}}"
  loop_control:
    loop_var: __zone
  when: >
    (firewalld_available is defined and
    firewalld_available == True) and
    proxy_squid.firewall_zones is defined and
    proxy_squid.port is defined

- name: configure firewall rules
  include_role:
    name: basic-host
    tasks_from: firewalld_rules.yml
  with_dict: "{{proxy_squid.firewall_rules}}"
  when: >
    (firewalld_available is defined and
    firewalld_available == True) and
    proxy_squid.firewall_rules is defined

- name: create squid configuration
  template:
    src: "{{__config}}.j2"
    dest: "{{proxy_squid.config_dir|default('/etc/squid')}}/{{__config}}"
    mode: 0640
  with_items:
    - cachemgr.conf
    - squid.conf
    - mime.conf
  loop_control:
    loop_var: __config
  notify: restart squid

- name: enable squid
  service: name=squid enabled=yes state=started
